POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "",
    "password": "",
    "email": ""
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###

GET http://localhost:3000/search
Authorization: Bearer 

###

POST http://localhost:3000/logout
Content-Type: application/json

{
    "token": ""
}